### ISSUE TITLE
Envvar 'Allowed Values' Enum?

### ISSUE THREAD

**Issue by andyt10** [flemay/envvars#15]
I don't know if this is trying to solve a problem in the wrong place, but I have reached a conclusion it might be useful to specify a list of allowed values for enums when using this tool. A validator of sorts:

Example: 
```
envvars:
  - name: ENV
    desc: Application stage (dev, qa, preprod, prod)
    tags:
      - deploy
    optional: true
    example: dev
    values:
        - dev
        - qa
        - preprod
        - prod
```

I'd be happy to flex my go muscles and contribute this, just want to get some input before I do :)
