### ISSUE TITLE
List of examples

### ISSUE THREAD

**Issue by aarongorka** [flemay/envvars#2]
It would be nice to pass a list of examples instead of being limited to one.

```yaml
envvars:
  - name: ENV
    description: Application environment
    examples:
      - prod
      - dev
    tags:
      - deploy
```
