### ISSUE TITLE
if example is empty, we still need the equal sign

### ISSUE THREAD

**Issue by sandyleo26** [flemay/envvars#6]
currently if we don't have an example 

```yaml
envvars:
  - name: AWS_DEFAULT_REGION
    desc: AWS Region to deploy to
    tags:
      - aws
```

the `.env` file will be generated like
```
AWS_DEFAULT_REGION
```

But i think it should be like
```
AWS_DEFAULT_REGION=
```

This can also prevent [issue](https://github.com/docker/compose/issues/7180#issuecomment-578775020) if i use `envvars envfile ` to generate a `.env` and later invoke `docker-compose` with it.

i can submit a small pr to get it fixed if you think it makes sense.
